export const FUNFAIRSHIFTS_REQUEST = 'FUNFAIRSHIFTS_REQUEST';
export const FUNFAIRSHIFTS_SORT = 'FUNFAIRSHIFTS_SORT';
export const FUNFAIRSHIFTS_SELECT = 'FUNFAIRSHIFTS_SELECT';
export const SEMAPHORES_REQUEST = 'SEMAPHORES_REQUEST';
export const SEMAPHORE_HOVER = 'SEMAPHORE_HOVER';
export const SEMAPHORE_LOCK = 'SEMAPHORE_LOCK';
export const SEMAPHORE_STATE_SUBMIT = 'SEMAPHORE_STATE_SUBMIT';
