export const FUNFAIRSHIFTS_REQUEST_SUCCESS = 'FUNFAIRSHIFTS_REQUEST_SUCCESS';
export const FUNFAIRSHIFTS_SORT = 'FUNFAIRSHIFTS_SORT';
export const FUNFAIRSHIFTS_SELECT = 'FUNFAIRSHIFTS_SELECT';
export const SEMAPHORES_REQUEST_SUCCESS = 'SEMAPHORES_REQUEST_SUCCESS';
export const SEMAPHORE_HOVER = 'SEMAPHORE_HOVER';
export const SEMAPHORE_LOCK = 'SEMAPHORE_LOCK';
export const SEMAPHORE_STATE_SUBMIT_SUCCESS = 'SEMAPHORE_STATE_SUBMIT_SUCCESS';
