export const CLASSNAME_SHORT = 'short';
export const CLASSNAME_MEDIUM = 'medium';
export const CLASSNAME_LONG = 'long';
export const CLASSNAME_HIGHLIGHT = 'highlight';

export const INDICATOR_SHORT = 'SHORT';
export const INDICATOR_MEDIUM = 'MEDIUM';
export const INDICATOR_LONG = 'LONG';

export const STATUS_MAP = {};
STATUS_MAP[INDICATOR_SHORT] = CLASSNAME_SHORT;
STATUS_MAP[INDICATOR_MEDIUM] = CLASSNAME_MEDIUM;
STATUS_MAP[INDICATOR_LONG] = CLASSNAME_LONG;

export const SEMAPHORE_MAP = {};
SEMAPHORE_MAP[INDICATOR_SHORT] = CLASSNAME_SHORT;
SEMAPHORE_MAP[INDICATOR_MEDIUM] = CLASSNAME_MEDIUM;
SEMAPHORE_MAP[INDICATOR_LONG] = CLASSNAME_LONG;

export const INDICATOR_PRIORITY = [INDICATOR_LONG, INDICATOR_MEDIUM, INDICATOR_SHORT];
